jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2

    - name: Install dependencies
      run: flutter pub get

    - name: Set up Kotlin
      run: |
        sudo apt-get update
        sudo apt-get install kotlin

    - name: Build APK
      run: flutter build apk --release
